apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  namespace: default
spec: 
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - web
          - fronend
  template:
    metadata:
      labels:
        app: fronend
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  