apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-dae 
  namespace: default
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
