apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  namespace: default
spec: 
  replicas: 3
  selector:
    app: web
  template:
    metadata:
      name: single
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
  
    